### ISSUE TITLE
Exception/Error handling

### ISSUE THREAD

**Issue by ghost** [vergecurrency/vDroid#18]
Proper Exception/Error handling

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/9467188/58352277-673a8680-7e6b-11e9-9c3d-e1cadca2de97.png)


Example Report

************ CAUSE OF ERROR ************

java.lang.Exception: Example Exception Message Code: 600
	at vergecurrency.vergewallet.view.ui.activity.firstlaunch.PaperkeyDistributionActivity.generateSeed(PaperkeyDistributionActivity.java:43)
	at vergecurrency.vergewallet.view.ui.activity.firstlaunch.PaperkeyDistributionActivity.onCreate(PaperkeyDistributionActivity.java:36)
	at android.app.Activity.performCreate(Activity.java:7698)
	at android.app.Activity.performCreate(Activity.java:7687)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1935)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7116)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:925)

************ DEVICE INFORMATION ***********
Brand: google13
Device: generic_x8613
Model: Android SDK built for x8613Id: QPP3.190404.015.A113
Product: sdk_gphone_x8613
************ FIRMWARE ************
SDK: Q - 2813Release: 1013Incremental: 550611613

**Comment by ghost** [comment]
Good or bad idea?

**Comment by 2lazy2debug** [comment]
Not bad idea but don't think it's optimal either. I'm concerned about the exception tbh I haven't encountered and the proper handling for this should be something else. But I agree on throwing this activity as a fallback.

**Comment by ghost** [comment]
are you concerned about the unhandled exceptions?

**Comment by ghost** [comment]
My implementation will catch any exception. I will register the DefaultExceptionHandler on each activity, viewModel  ...

java.lang.Thread.setUncaughtExceptionHandler()

**Comment by ghost** [comment]
Do you prefer sending error reports to an api?

**Comment by 2lazy2debug** [comment]
I'm concerned about the exception indeed, can you open up an issue for this exception? 
As said, I like the idea of having this feature for unhandled exception. Open a PR and I'll merge it, thanks for the contribution :)
